status = [
  "formatting",
  "clippy",
  "check_maker_frontend",
  "build_and_test_taker_frontend",
  "build_and_test_maker_frontend",
  "test_daemons (ubuntu-latest)",
  "test_daemons (macos-latest)",
  "daemons_arm_build",
]
