[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[alias]
dev-maker = "run --bin maker -- --instrumentation --password dev testnet"
dev-taker = "run --bin taker -- --instrumentation --maker localhost:10000 --maker-id 10d4ba2ac3f7a22da4009d813ff1bc3f404dfe2cc93a32bedf1512aa9951c95e --maker-peer-id 12D3KooWDjzHna3pNi1Bt1DoRfrpsBREykJKXDRDxXvhJNAdDZEk --password dev testnet" # Maker ID matches seed found in `testnet/maker_seed`

dev-maker-headless = "run --bin maker -- --instrumentation --password dev --headless testnet"
dev-taker-headless = "run --bin taker -- --instrumentation --maker localhost:10000 --maker-id 10d4ba2ac3f7a22da4009d813ff1bc3f404dfe2cc93a32bedf1512aa9951c95e --maker-peer-id 12D3KooWDjzHna3pNi1Bt1DoRfrpsBREykJKXDRDxXvhJNAdDZEk --password dev --headless testnet" # Maker ID matches seed found in `testnet/maker_seed`

# Inspired by https://github.com/EmbarkStudios/rust-ecosystem/pull/68.
# tokio_unstable enabled for tokio_console and tokio_metrics only
[build]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Wclippy::disallowed_methods",
  "-Wclippy::dbg_macro",
  "-Wclippy::print_stderr",
  "-Wclippy::print_stdout",
  "-Wunused-import-braces",
  "-Wmissing-copy-implementations",
  "-Wunused-import-braces",
  "-Wunused-qualifications",
]
