name: CI

on:
  pull_request:
  push:
    branches:
      - 'staging'
      - 'master'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dprint/check@v1.5

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo clippy --workspace --all-targets -- -D warnings

  build_frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: yarn install
      - run: yarn run eslint
      - run: yarn build

  test_daemons:
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-apple-darwin ]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo build --all-targets --all-features
      - run: cargo test --workspace
      - name: Smoke test ${{ matrix.target }} binary
        run: |
          target/debug/maker --data-dir=/tmp/maker --generate-seed &
          sleep 5s # Wait for maker to start
          target/debug/taker --data-dir=/tmp/taker --generate-seed &
          sleep 5s # Wait for taker to start
          curl --fail http://localhost:8000/alive
